export const CREATE_LIBRARY_REQUEST = 'CREATE_LIBRARY_REQUEST'
export const LIBRARY_CREATED = 'LIBRARY_CREATED'
export const LIBRARY_CREATION_FAILED = 'LIBRARY_CREATION_FAILED'
export const ADD_BOOKS_REQUEST = 'ADD_BOOKS_REQUEST'
export const ADDED_BOOKS = 'ADDED_BOOKS'
export const ADD_BOOKS_FAILED = 'ADD_BOOKS_FAILED'
export const LOAD_LIIBRARY_REQUEST = 'LOAD_LIIBRARY_REQUEST'
export const LIBRARY_LOADED = 'LIBRARY_LOADED'
export const LOAD_LIBRARY_FAILED = 'LOAD_LIBRARY_FAILED'
export const ACCEPT_REJECT_REQUEST = 'ACCEPT_REJECT_REQUEST'
export const ACCPETED_REJECTED = 'ACCPETED_REJECTED'
export const ACCEPET_REJECT_FAIL = 'ACCEPET_REJECT_FAIL'


