export const GET_LIBRARIES_REQUEST = 'GET_LIBRARIES_REQUEST'
export const GOT_LIBRARIES = 'GOT_LIBRARIES'
export const GET_LIBRARIES_FAIL = 'GET_LIBRARIES_FAIL'
export const SEND_REQUEST_STARTED = 'SEND_REQUEST_STARTED'
export const SEND_REQUEST_DONE = 'SEND_REQUEST_DONE'
export const SEND_REQUEST_FAILED = 'SEND_REQUEST_FAILED'



