let config = {
  MONGO_URL: process.env.MONOGO_URL,
  MONGO_PORT: 27017,
  REDIS_PORT: 6379,
  TOKEN_EXPRIES_TIME: "7d",
  PASSWORD_HASH_LENGTH: 10,
  DB_CONNECTION_RETTEMPT_LIMIT_NODE: 3,
  RANDOM_NUMBER_LENGTH: 6,
  JWT_SECRET: process.env.JWT_SECRET,
  GOOGLE_CLIENT_ID:
    process.env.GOOGLE_CLIENT_ID,
  GOOGLE_SECRET: process.env.GOOGLE_SECRET,
  GOOGLE_API_KEY: process.env.GOOGLE_API_KEY
};

module.exports = config;
